# Generated by Django 3.2.9 on 2021-11-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectis',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
