# Generated by Django 3.2.9 on 2021-11-26 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vectis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servitium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('credit', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='servitium_owner', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ManyToManyField(through='thiorkApp.Inquiry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='servitium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thiorkApp.servitium'),
        ),
        migrations.CreateModel(
            name='Eventum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('credit', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('attendes', models.ManyToManyField(through='thiorkApp.Attendance', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventum_host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='eventum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thiorkApp.eventum'),
        ),
    ]
