# Generated by Django 3.2.9 on 2021-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectis',
            name='credit',
            field=models.IntegerField(default=5),
        ),
    ]
