# Generated by Django 3.2.9 on 2021-12-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectis',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
