# Generated by Django 3.2.9 on 2021-12-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servitium',
            name='city',
            field=models.CharField(default='istanbul', max_length=255),
        ),
    ]
