# Generated by Django 3.2.9 on 2021-12-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0002_alter_vectis_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectis',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
