# Generated by Django 4.0 on 2021-12-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0002_servitium_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servitium',
            name='city',
            field=models.CharField(default='Istanbul', max_length=255),
        ),
        migrations.AlterField(
            model_name='servitium',
            name='status',
            field=models.CharField(default='Available', max_length=200),
        ),
    ]
