# Generated by Django 3.2.9 on 2021-12-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0003_alter_vectis_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectis',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photos/%Y/%m/%d/'),
        ),
    ]
