# Generated by Django 4.0 on 2021-12-30 21:48

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0003_alter_servitium_city_alter_servitium_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventum',
            name='credit',
        ),
        migrations.AddField(
            model_name='eventum',
            name='city',
            field=models.CharField(default='Istanbul', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventum',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
