# Generated by Django 4.0 on 2021-12-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0004_remove_eventum_credit_eventum_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventum',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
