# Generated by Django 4.0 on 2021-12-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0005_alter_eventum_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventum',
            name='max_number_of_attendees',
            field=models.IntegerField(default=5),
        ),
    ]
