# Generated by Django 4.0 on 2021-12-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiorkApp', '0006_eventum_max_number_of_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventum',
            name='status',
            field=models.CharField(default='Available', max_length=200),
        ),
    ]
